### PR TITLE
Fix/do not use string as event data

### PR DESCRIPTION
**Pull request by jkoenig134**

### CODE REVIEW

**Comment by Milena-Czierlinski** [comment]
How does the string cause problems exactly?

**Comment by slavistan** [comment]
`npm run build` fails at the `build:schemas` step. Does this work on your ends?

**Comment by jkoenig134** [comment]
We have problems with node 22.5 wich came out today. All pipelines are failing.

**Comment by jkoenig134** [comment]
> How does the string cause problems exactly?

It's away from how we use the data everywhere else and therefore simply not handled correctly in the bridge.

**Review by Milena-Czierlinski — APPROVED** [review]

**Review by britsta — COMMENTED** [review]
The line `await expect(services1.eventBus).toHavePublished(RelationshipDecomposedBySelfEvent, (e) => e.data === relationshipId);` of the test `relationship should be decomposed` of the file `relationships.test.ts` needs to be adjusted.

**Review by Milena-Czierlinski — APPROVED** [review]

**Pull request merged**
