### PR TITLE
Package versions does not land in the buildInformation

### PR DESCRIPTION
**Pull request by jkoenig134**
# Readiness checklist

-   [ ] I added/updated tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

# Description

image

### CODE REVIEW

**Review by britsta — COMMENTED** [review]
Out of curiosity, what is the advantage of this change? 🐌

**Review by Milena-Czierlinski — APPROVED** [review]

**Comment by jkoenig134** [comment]
As you see in the description of the PR the CI was bugged, this fixes it :)

**Comment by britsta** [comment]
> As you see in the description of the PR the CI was bugged, this fixes it :)

Ohh, I hadn't seen the photo, got it!

**Comment by jkoenig134** [comment]
Yeah, when I switched to GitHub releases i TOTALLY forgot about this :(

**Pull request merged**
