### PR TITLE
Remove unused injected controller

### PR DESCRIPTION
**Pull request by Milena-Czierlinski**
# Readiness checklist

-   [ ] I added/updated tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.
-   [x] I self-reviewed the PR.

### CODE REVIEW

**Comment by jkoenig134** [comment]
Hmmmmm, why is this unused??

**Comment by Milena-Czierlinski** [comment]
It was added in #212 . Maybe @britsta used in for some kind of validation and then moved it elsewhere and forgot to remove it. 🤔 And we didn't see it in our review. I am also surprised that we don't get some kind of error.

**Comment by jkoenig134** [comment]
There's an error popping up?

**Review by jkoenig134 — APPROVED** [review]

**Comment by Milena-Czierlinski** [comment]
> There's an error popping up?

Where?

**Comment by jkoenig134** [comment]
> > There's an error popping up?
> 
> Where?

You wrote `I am also surprised that we don't get some kind of error`, so you started to talk about an error 😅

**Comment by Milena-Czierlinski** [comment]
Yes, but I said there is **no** error popping up. And then you asked `There is an error popping up?`. 😅 

I wish there was an error popping up. Do you know why there isn't?

**Comment by jkoenig134** [comment]
Oh, lol. Yeah eslint doesn't tracks these kind of unused vars.

**Pull request merged**
